name: codeforecon
channels:
  - conda-forge
dependencies:
  - jupyter
  - numpy
  - pandas
  - pip
  - python=3.8
  - pyyaml
  - scipy
  - seaborn
  - statsmodels
  - tqdm
  - yaml
  - pycodestyle
  - pyarrow
  - geopandas
  - autopep8
  - geoplot
  - nltk
  - arrow
  - osmnx
  - pandas-datareader
  - pandasdmx
  - pdfminer.six
  - jupyter-book
  - pytest
  - rich
  - pyinstrument
  - loguru
  - pre-commit
  - pandera
  - linearmodels
  - sympy
  - pingouin
  - jax
  - plotly
  - spacy
  - pandas-profiling
  - plotnine
  - altair
  - datatable
  - cerberus
  - great-expectations
  - dagster
  - waterfallcharts
  - matplotlib-venn
  - pywaffle
  - joypy
  - jupyterlab
  - textstat
  - nbstripout
  - vega_datasets
  - ghp-import
  - colorcet
  - requests-cache
  - pip
  - arch-py
  - workalendar
  - wordcloud
  - mkl
  - mkl-service
  - bambi
  - pdftotext
  - bottleneck
  - openpyxl
  - python-slugify
  - pymc
  - umap-learn
  - pip:
    - specification_curve
    - stargazer
    - matplotlib-scalebar
    - black-nb
    - pyhdfe
    - skimpy
    - graphviz
    - ruptures
    - sqlmodel
    - ibis-framework
    - binsreg
    - feature-engine
